// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: google/cloud/runtimeconfig/v1beta1/runtimeconfig.proto
// Original file comments:
// Copyright 2016 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_google_2fcloud_2fruntimeconfig_2fv1beta1_2fruntimeconfig_2eproto__INCLUDED
#define GRPC_google_2fcloud_2fruntimeconfig_2fv1beta1_2fruntimeconfig_2eproto__INCLUDED

#include "google/cloud/runtimeconfig/v1beta1/runtimeconfig.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace google {
namespace cloud {
namespace runtimeconfig {
namespace v1beta1 {

// RuntimeConfig API represents configuration objects and operations on those
// configuration objects.
// RuntimeConfig objects consist of Variables logically grouped in the those
// objects.
// Variables are simple key-value pairs. Variables can be watched for changes or
// deletions. Variable key can be hieararchical, e.g. ports/serving_port,
// ports/monitoring_port, etc. Variable names can be hierarchical. No variable
// name can be prefix of another.
// Config objects represent logical containers for variables, e.g. flags,
// passwords, etc.
class RuntimeConfigManager GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Lists all the RuntimeConfig resources within project.
    virtual ::grpc::Status ListConfigs(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListConfigsRequest& request, ::google::cloud::runtimeconfig::v1beta1::ListConfigsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::ListConfigsResponse>> AsyncListConfigs(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListConfigsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::ListConfigsResponse>>(AsyncListConfigsRaw(context, request, cq));
    }
    // Gets information about a RuntimeConfig resource.
    virtual ::grpc::Status GetConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetConfigRequest& request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>> AsyncGetConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>>(AsyncGetConfigRaw(context, request, cq));
    }
    // Creates a new RuntimeConfig resource. The configuration name must be
    // unique within project.
    virtual ::grpc::Status CreateConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateConfigRequest& request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>> AsyncCreateConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>>(AsyncCreateConfigRaw(context, request, cq));
    }
    // Updates a RuntimeConfig resource. The configuration must exist beforehand.
    virtual ::grpc::Status UpdateConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateConfigRequest& request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>> AsyncUpdateConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>>(AsyncUpdateConfigRaw(context, request, cq));
    }
    // Deletes a RuntimeConfig resource.
    virtual ::grpc::Status DeleteConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteConfigRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncDeleteConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncDeleteConfigRaw(context, request, cq));
    }
    // Lists variables within given a configuration, matching any provided filters.
    // This only lists variable names, not the values.
    virtual ::grpc::Status ListVariables(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListVariablesRequest& request, ::google::cloud::runtimeconfig::v1beta1::ListVariablesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::ListVariablesResponse>> AsyncListVariables(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListVariablesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::ListVariablesResponse>>(AsyncListVariablesRaw(context, request, cq));
    }
    // Gets information about a single variable.
    virtual ::grpc::Status GetVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetVariableRequest& request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Variable>> AsyncGetVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetVariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Variable>>(AsyncGetVariableRaw(context, request, cq));
    }
    // Watches a specific variable and waits for a change in the variable's value.
    // When there is a change, this method returns the new value or times out.
    //
    // If a variable is deleted while being watched, the `variableState` state is
    // set to `DELETED` and the method returns the last known variable `value`.
    //
    // If you set the deadline for watching to a larger value than internal timeout
    // (60 seconds), the current variable value is returned and the `variableState`
    // will be `VARIABLE_STATE_UNSPECIFIED`.
    //
    // To learn more about creating a watcher, read the
    // [Watching a Variable for Changes](/deployment-manager/runtime-configurator/watching-a-variable)
    // documentation.
    virtual ::grpc::Status WatchVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::WatchVariableRequest& request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Variable>> AsyncWatchVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::WatchVariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Variable>>(AsyncWatchVariableRaw(context, request, cq));
    }
    // Creates a variable within the given configuration. You cannot create
    // a variable with a name that is a prefix of an existing variable name, or a
    // name that has an existing variable name as a prefix.
    //
    // To learn more about creating a variable, read the
    // [Setting and Getting Data](/deployment-manager/runtime-configurator/set-and-get-variables)
    // documentation.
    virtual ::grpc::Status CreateVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateVariableRequest& request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Variable>> AsyncCreateVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateVariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Variable>>(AsyncCreateVariableRaw(context, request, cq));
    }
    // Updates an existing variable with a new value.
    virtual ::grpc::Status UpdateVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateVariableRequest& request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Variable>> AsyncUpdateVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateVariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Variable>>(AsyncUpdateVariableRaw(context, request, cq));
    }
    // Deletes a variable or multiple variables.
    //
    // If you specify a variable name, then that variable is deleted. If you
    // specify a prefix and `recursive` is true, then all variables with that
    // prefix are deleted. You must set a `recursive` to true if you delete
    // variables by prefix.
    virtual ::grpc::Status DeleteVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteVariableRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncDeleteVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteVariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncDeleteVariableRaw(context, request, cq));
    }
    // List waiters within the given configuration.
    virtual ::grpc::Status ListWaiters(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListWaitersRequest& request, ::google::cloud::runtimeconfig::v1beta1::ListWaitersResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::ListWaitersResponse>> AsyncListWaiters(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListWaitersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::ListWaitersResponse>>(AsyncListWaitersRaw(context, request, cq));
    }
    // Gets information about a single waiter.
    virtual ::grpc::Status GetWaiter(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetWaiterRequest& request, ::google::cloud::runtimeconfig::v1beta1::Waiter* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Waiter>> AsyncGetWaiter(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetWaiterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Waiter>>(AsyncGetWaiterRaw(context, request, cq));
    }
    // Creates a Waiter resource. This operation returns a long-running Operation
    // resource which can be polled for completion. However, a waiter with the
    // given name will exist (and can be retrieved) prior to the operation
    // completing. If the operation fails, the failed Waiter resource will
    // still exist and must be deleted prior to subsequent creation attempts.
    virtual ::grpc::Status CreateWaiter(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateWaiterRequest& request, ::google::longrunning::Operation* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>> AsyncCreateWaiter(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateWaiterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>>(AsyncCreateWaiterRaw(context, request, cq));
    }
    // Deletes the waiter with the specified name.
    virtual ::grpc::Status DeleteWaiter(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteWaiterRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncDeleteWaiter(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteWaiterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncDeleteWaiterRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::ListConfigsResponse>* AsyncListConfigsRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListConfigsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>* AsyncGetConfigRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>* AsyncCreateConfigRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>* AsyncUpdateConfigRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncDeleteConfigRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::ListVariablesResponse>* AsyncListVariablesRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListVariablesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Variable>* AsyncGetVariableRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetVariableRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Variable>* AsyncWatchVariableRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::WatchVariableRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Variable>* AsyncCreateVariableRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateVariableRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Variable>* AsyncUpdateVariableRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateVariableRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncDeleteVariableRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteVariableRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::ListWaitersResponse>* AsyncListWaitersRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListWaitersRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::cloud::runtimeconfig::v1beta1::Waiter>* AsyncGetWaiterRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetWaiterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::longrunning::Operation>* AsyncCreateWaiterRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateWaiterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncDeleteWaiterRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteWaiterRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ListConfigs(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListConfigsRequest& request, ::google::cloud::runtimeconfig::v1beta1::ListConfigsResponse* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::ListConfigsResponse>> AsyncListConfigs(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListConfigsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::ListConfigsResponse>>(AsyncListConfigsRaw(context, request, cq));
    }
    ::grpc::Status GetConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetConfigRequest& request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>> AsyncGetConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>>(AsyncGetConfigRaw(context, request, cq));
    }
    ::grpc::Status CreateConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateConfigRequest& request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>> AsyncCreateConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>>(AsyncCreateConfigRaw(context, request, cq));
    }
    ::grpc::Status UpdateConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateConfigRequest& request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>> AsyncUpdateConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>>(AsyncUpdateConfigRaw(context, request, cq));
    }
    ::grpc::Status DeleteConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteConfigRequest& request, ::google::protobuf::Empty* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncDeleteConfig(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncDeleteConfigRaw(context, request, cq));
    }
    ::grpc::Status ListVariables(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListVariablesRequest& request, ::google::cloud::runtimeconfig::v1beta1::ListVariablesResponse* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::ListVariablesResponse>> AsyncListVariables(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListVariablesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::ListVariablesResponse>>(AsyncListVariablesRaw(context, request, cq));
    }
    ::grpc::Status GetVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetVariableRequest& request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Variable>> AsyncGetVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetVariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Variable>>(AsyncGetVariableRaw(context, request, cq));
    }
    ::grpc::Status WatchVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::WatchVariableRequest& request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Variable>> AsyncWatchVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::WatchVariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Variable>>(AsyncWatchVariableRaw(context, request, cq));
    }
    ::grpc::Status CreateVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateVariableRequest& request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Variable>> AsyncCreateVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateVariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Variable>>(AsyncCreateVariableRaw(context, request, cq));
    }
    ::grpc::Status UpdateVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateVariableRequest& request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Variable>> AsyncUpdateVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateVariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Variable>>(AsyncUpdateVariableRaw(context, request, cq));
    }
    ::grpc::Status DeleteVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteVariableRequest& request, ::google::protobuf::Empty* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncDeleteVariable(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteVariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncDeleteVariableRaw(context, request, cq));
    }
    ::grpc::Status ListWaiters(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListWaitersRequest& request, ::google::cloud::runtimeconfig::v1beta1::ListWaitersResponse* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::ListWaitersResponse>> AsyncListWaiters(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListWaitersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::ListWaitersResponse>>(AsyncListWaitersRaw(context, request, cq));
    }
    ::grpc::Status GetWaiter(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetWaiterRequest& request, ::google::cloud::runtimeconfig::v1beta1::Waiter* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Waiter>> AsyncGetWaiter(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetWaiterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Waiter>>(AsyncGetWaiterRaw(context, request, cq));
    }
    ::grpc::Status CreateWaiter(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateWaiterRequest& request, ::google::longrunning::Operation* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>> AsyncCreateWaiter(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateWaiterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>>(AsyncCreateWaiterRaw(context, request, cq));
    }
    ::grpc::Status DeleteWaiter(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteWaiterRequest& request, ::google::protobuf::Empty* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncDeleteWaiter(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteWaiterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncDeleteWaiterRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::ListConfigsResponse>* AsyncListConfigsRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListConfigsRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>* AsyncGetConfigRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetConfigRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>* AsyncCreateConfigRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateConfigRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>* AsyncUpdateConfigRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateConfigRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncDeleteConfigRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteConfigRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::ListVariablesResponse>* AsyncListVariablesRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListVariablesRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Variable>* AsyncGetVariableRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetVariableRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Variable>* AsyncWatchVariableRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::WatchVariableRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Variable>* AsyncCreateVariableRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateVariableRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Variable>* AsyncUpdateVariableRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateVariableRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncDeleteVariableRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteVariableRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::ListWaitersResponse>* AsyncListWaitersRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListWaitersRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::cloud::runtimeconfig::v1beta1::Waiter>* AsyncGetWaiterRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetWaiterRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::longrunning::Operation>* AsyncCreateWaiterRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateWaiterRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncDeleteWaiterRaw(::grpc::ClientContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteWaiterRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_ListConfigs_;
    const ::grpc::RpcMethod rpcmethod_GetConfig_;
    const ::grpc::RpcMethod rpcmethod_CreateConfig_;
    const ::grpc::RpcMethod rpcmethod_UpdateConfig_;
    const ::grpc::RpcMethod rpcmethod_DeleteConfig_;
    const ::grpc::RpcMethod rpcmethod_ListVariables_;
    const ::grpc::RpcMethod rpcmethod_GetVariable_;
    const ::grpc::RpcMethod rpcmethod_WatchVariable_;
    const ::grpc::RpcMethod rpcmethod_CreateVariable_;
    const ::grpc::RpcMethod rpcmethod_UpdateVariable_;
    const ::grpc::RpcMethod rpcmethod_DeleteVariable_;
    const ::grpc::RpcMethod rpcmethod_ListWaiters_;
    const ::grpc::RpcMethod rpcmethod_GetWaiter_;
    const ::grpc::RpcMethod rpcmethod_CreateWaiter_;
    const ::grpc::RpcMethod rpcmethod_DeleteWaiter_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Lists all the RuntimeConfig resources within project.
    virtual ::grpc::Status ListConfigs(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListConfigsRequest* request, ::google::cloud::runtimeconfig::v1beta1::ListConfigsResponse* response);
    // Gets information about a RuntimeConfig resource.
    virtual ::grpc::Status GetConfig(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetConfigRequest* request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response);
    // Creates a new RuntimeConfig resource. The configuration name must be
    // unique within project.
    virtual ::grpc::Status CreateConfig(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateConfigRequest* request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response);
    // Updates a RuntimeConfig resource. The configuration must exist beforehand.
    virtual ::grpc::Status UpdateConfig(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateConfigRequest* request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response);
    // Deletes a RuntimeConfig resource.
    virtual ::grpc::Status DeleteConfig(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteConfigRequest* request, ::google::protobuf::Empty* response);
    // Lists variables within given a configuration, matching any provided filters.
    // This only lists variable names, not the values.
    virtual ::grpc::Status ListVariables(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListVariablesRequest* request, ::google::cloud::runtimeconfig::v1beta1::ListVariablesResponse* response);
    // Gets information about a single variable.
    virtual ::grpc::Status GetVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetVariableRequest* request, ::google::cloud::runtimeconfig::v1beta1::Variable* response);
    // Watches a specific variable and waits for a change in the variable's value.
    // When there is a change, this method returns the new value or times out.
    //
    // If a variable is deleted while being watched, the `variableState` state is
    // set to `DELETED` and the method returns the last known variable `value`.
    //
    // If you set the deadline for watching to a larger value than internal timeout
    // (60 seconds), the current variable value is returned and the `variableState`
    // will be `VARIABLE_STATE_UNSPECIFIED`.
    //
    // To learn more about creating a watcher, read the
    // [Watching a Variable for Changes](/deployment-manager/runtime-configurator/watching-a-variable)
    // documentation.
    virtual ::grpc::Status WatchVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::WatchVariableRequest* request, ::google::cloud::runtimeconfig::v1beta1::Variable* response);
    // Creates a variable within the given configuration. You cannot create
    // a variable with a name that is a prefix of an existing variable name, or a
    // name that has an existing variable name as a prefix.
    //
    // To learn more about creating a variable, read the
    // [Setting and Getting Data](/deployment-manager/runtime-configurator/set-and-get-variables)
    // documentation.
    virtual ::grpc::Status CreateVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateVariableRequest* request, ::google::cloud::runtimeconfig::v1beta1::Variable* response);
    // Updates an existing variable with a new value.
    virtual ::grpc::Status UpdateVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateVariableRequest* request, ::google::cloud::runtimeconfig::v1beta1::Variable* response);
    // Deletes a variable or multiple variables.
    //
    // If you specify a variable name, then that variable is deleted. If you
    // specify a prefix and `recursive` is true, then all variables with that
    // prefix are deleted. You must set a `recursive` to true if you delete
    // variables by prefix.
    virtual ::grpc::Status DeleteVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteVariableRequest* request, ::google::protobuf::Empty* response);
    // List waiters within the given configuration.
    virtual ::grpc::Status ListWaiters(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListWaitersRequest* request, ::google::cloud::runtimeconfig::v1beta1::ListWaitersResponse* response);
    // Gets information about a single waiter.
    virtual ::grpc::Status GetWaiter(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetWaiterRequest* request, ::google::cloud::runtimeconfig::v1beta1::Waiter* response);
    // Creates a Waiter resource. This operation returns a long-running Operation
    // resource which can be polled for completion. However, a waiter with the
    // given name will exist (and can be retrieved) prior to the operation
    // completing. If the operation fails, the failed Waiter resource will
    // still exist and must be deleted prior to subsequent creation attempts.
    virtual ::grpc::Status CreateWaiter(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateWaiterRequest* request, ::google::longrunning::Operation* response);
    // Deletes the waiter with the specified name.
    virtual ::grpc::Status DeleteWaiter(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteWaiterRequest* request, ::google::protobuf::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListConfigs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ListConfigs() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListConfigs() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListConfigs(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListConfigsRequest* request, ::google::cloud::runtimeconfig::v1beta1::ListConfigsResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListConfigs(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::ListConfigsRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::runtimeconfig::v1beta1::ListConfigsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetConfig() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetConfig() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetConfig(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetConfigRequest* request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetConfig(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::GetConfigRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_CreateConfig() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_CreateConfig() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateConfig(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateConfigRequest* request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateConfig(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::CreateConfigRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_UpdateConfig() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_UpdateConfig() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateConfig(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateConfigRequest* request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateConfig(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::UpdateConfigRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_DeleteConfig() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_DeleteConfig() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteConfig(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteConfigRequest* request, ::google::protobuf::Empty* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteConfig(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::DeleteConfigRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ListVariables() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_ListVariables() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListVariables(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListVariablesRequest* request, ::google::cloud::runtimeconfig::v1beta1::ListVariablesResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListVariables(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::ListVariablesRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::runtimeconfig::v1beta1::ListVariablesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetVariable() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_GetVariable() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetVariableRequest* request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetVariable(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::GetVariableRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::runtimeconfig::v1beta1::Variable>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_WatchVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_WatchVariable() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_WatchVariable() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WatchVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::WatchVariableRequest* request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWatchVariable(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::WatchVariableRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::runtimeconfig::v1beta1::Variable>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_CreateVariable() {
      ::grpc::Service::MarkMethodAsync(8);
    }
    ~WithAsyncMethod_CreateVariable() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateVariableRequest* request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateVariable(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::CreateVariableRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::runtimeconfig::v1beta1::Variable>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(8, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_UpdateVariable() {
      ::grpc::Service::MarkMethodAsync(9);
    }
    ~WithAsyncMethod_UpdateVariable() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateVariableRequest* request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateVariable(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::UpdateVariableRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::runtimeconfig::v1beta1::Variable>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(9, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_DeleteVariable() {
      ::grpc::Service::MarkMethodAsync(10);
    }
    ~WithAsyncMethod_DeleteVariable() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteVariableRequest* request, ::google::protobuf::Empty* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteVariable(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::DeleteVariableRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(10, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListWaiters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ListWaiters() {
      ::grpc::Service::MarkMethodAsync(11);
    }
    ~WithAsyncMethod_ListWaiters() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListWaiters(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListWaitersRequest* request, ::google::cloud::runtimeconfig::v1beta1::ListWaitersResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListWaiters(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::ListWaitersRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::runtimeconfig::v1beta1::ListWaitersResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(11, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetWaiter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetWaiter() {
      ::grpc::Service::MarkMethodAsync(12);
    }
    ~WithAsyncMethod_GetWaiter() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWaiter(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetWaiterRequest* request, ::google::cloud::runtimeconfig::v1beta1::Waiter* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetWaiter(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::GetWaiterRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::cloud::runtimeconfig::v1beta1::Waiter>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(12, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateWaiter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_CreateWaiter() {
      ::grpc::Service::MarkMethodAsync(13);
    }
    ~WithAsyncMethod_CreateWaiter() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateWaiter(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateWaiterRequest* request, ::google::longrunning::Operation* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateWaiter(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::CreateWaiterRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::longrunning::Operation>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(13, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteWaiter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_DeleteWaiter() {
      ::grpc::Service::MarkMethodAsync(14);
    }
    ~WithAsyncMethod_DeleteWaiter() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteWaiter(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteWaiterRequest* request, ::google::protobuf::Empty* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteWaiter(::grpc::ServerContext* context, ::google::cloud::runtimeconfig::v1beta1::DeleteWaiterRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(14, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListConfigs<WithAsyncMethod_GetConfig<WithAsyncMethod_CreateConfig<WithAsyncMethod_UpdateConfig<WithAsyncMethod_DeleteConfig<WithAsyncMethod_ListVariables<WithAsyncMethod_GetVariable<WithAsyncMethod_WatchVariable<WithAsyncMethod_CreateVariable<WithAsyncMethod_UpdateVariable<WithAsyncMethod_DeleteVariable<WithAsyncMethod_ListWaiters<WithAsyncMethod_GetWaiter<WithAsyncMethod_CreateWaiter<WithAsyncMethod_DeleteWaiter<Service > > > > > > > > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_ListConfigs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ListConfigs() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListConfigs() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListConfigs(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListConfigsRequest* request, ::google::cloud::runtimeconfig::v1beta1::ListConfigsResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetConfig() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetConfig() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetConfig(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetConfigRequest* request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_CreateConfig() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_CreateConfig() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateConfig(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateConfigRequest* request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_UpdateConfig() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_UpdateConfig() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateConfig(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateConfigRequest* request, ::google::cloud::runtimeconfig::v1beta1::RuntimeConfig* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_DeleteConfig() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_DeleteConfig() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteConfig(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteConfigRequest* request, ::google::protobuf::Empty* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ListVariables() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_ListVariables() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListVariables(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListVariablesRequest* request, ::google::cloud::runtimeconfig::v1beta1::ListVariablesResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetVariable() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_GetVariable() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetVariableRequest* request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_WatchVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_WatchVariable() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_WatchVariable() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WatchVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::WatchVariableRequest* request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_CreateVariable() {
      ::grpc::Service::MarkMethodGeneric(8);
    }
    ~WithGenericMethod_CreateVariable() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateVariableRequest* request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_UpdateVariable() {
      ::grpc::Service::MarkMethodGeneric(9);
    }
    ~WithGenericMethod_UpdateVariable() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::UpdateVariableRequest* request, ::google::cloud::runtimeconfig::v1beta1::Variable* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_DeleteVariable() {
      ::grpc::Service::MarkMethodGeneric(10);
    }
    ~WithGenericMethod_DeleteVariable() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteVariable(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteVariableRequest* request, ::google::protobuf::Empty* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListWaiters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ListWaiters() {
      ::grpc::Service::MarkMethodGeneric(11);
    }
    ~WithGenericMethod_ListWaiters() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListWaiters(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::ListWaitersRequest* request, ::google::cloud::runtimeconfig::v1beta1::ListWaitersResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetWaiter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetWaiter() {
      ::grpc::Service::MarkMethodGeneric(12);
    }
    ~WithGenericMethod_GetWaiter() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWaiter(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::GetWaiterRequest* request, ::google::cloud::runtimeconfig::v1beta1::Waiter* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateWaiter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_CreateWaiter() {
      ::grpc::Service::MarkMethodGeneric(13);
    }
    ~WithGenericMethod_CreateWaiter() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateWaiter(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::CreateWaiterRequest* request, ::google::longrunning::Operation* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteWaiter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_DeleteWaiter() {
      ::grpc::Service::MarkMethodGeneric(14);
    }
    ~WithGenericMethod_DeleteWaiter() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteWaiter(::grpc::ServerContext* context, const ::google::cloud::runtimeconfig::v1beta1::DeleteWaiterRequest* request, ::google::protobuf::Empty* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace v1beta1
}  // namespace runtimeconfig
}  // namespace cloud
}  // namespace google


#endif  // GRPC_google_2fcloud_2fruntimeconfig_2fv1beta1_2fruntimeconfig_2eproto__INCLUDED
