// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/distribution.proto

#ifndef PROTOBUF_google_2fapi_2fdistribution_2eproto__INCLUDED
#define PROTOBUF_google_2fapi_2fdistribution_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "google/api/annotations.pb.h"
#include <google/protobuf/any.pb.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)

namespace google {
namespace api {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_google_2fapi_2fdistribution_2eproto();
void protobuf_AssignDesc_google_2fapi_2fdistribution_2eproto();
void protobuf_ShutdownFile_google_2fapi_2fdistribution_2eproto();

class Distribution;
class Distribution_BucketOptions;
class Distribution_BucketOptions_Explicit;
class Distribution_BucketOptions_Exponential;
class Distribution_BucketOptions_Linear;
class Distribution_Range;

// ===================================================================

class Distribution_Range : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.api.Distribution.Range) */ {
 public:
  Distribution_Range();
  virtual ~Distribution_Range();

  Distribution_Range(const Distribution_Range& from);

  inline Distribution_Range& operator=(const Distribution_Range& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Distribution_Range& default_instance();

  void Swap(Distribution_Range* other);

  // implements Message ----------------------------------------------

  inline Distribution_Range* New() const { return New(NULL); }

  Distribution_Range* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Distribution_Range& from);
  void MergeFrom(const Distribution_Range& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Distribution_Range* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double min = 1;
  void clear_min();
  static const int kMinFieldNumber = 1;
  double min() const;
  void set_min(double value);

  // optional double max = 2;
  void clear_max();
  static const int kMaxFieldNumber = 2;
  double max() const;
  void set_max(double value);

  // @@protoc_insertion_point(class_scope:google.api.Distribution.Range)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double min_;
  double max_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2fapi_2fdistribution_2eproto();
  friend void protobuf_AssignDesc_google_2fapi_2fdistribution_2eproto();
  friend void protobuf_ShutdownFile_google_2fapi_2fdistribution_2eproto();

  void InitAsDefaultInstance();
  static Distribution_Range* default_instance_;
};
// -------------------------------------------------------------------

class Distribution_BucketOptions_Linear : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.api.Distribution.BucketOptions.Linear) */ {
 public:
  Distribution_BucketOptions_Linear();
  virtual ~Distribution_BucketOptions_Linear();

  Distribution_BucketOptions_Linear(const Distribution_BucketOptions_Linear& from);

  inline Distribution_BucketOptions_Linear& operator=(const Distribution_BucketOptions_Linear& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Distribution_BucketOptions_Linear& default_instance();

  void Swap(Distribution_BucketOptions_Linear* other);

  // implements Message ----------------------------------------------

  inline Distribution_BucketOptions_Linear* New() const { return New(NULL); }

  Distribution_BucketOptions_Linear* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Distribution_BucketOptions_Linear& from);
  void MergeFrom(const Distribution_BucketOptions_Linear& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Distribution_BucketOptions_Linear* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 num_finite_buckets = 1;
  void clear_num_finite_buckets();
  static const int kNumFiniteBucketsFieldNumber = 1;
  ::google::protobuf::int32 num_finite_buckets() const;
  void set_num_finite_buckets(::google::protobuf::int32 value);

  // optional double width = 2;
  void clear_width();
  static const int kWidthFieldNumber = 2;
  double width() const;
  void set_width(double value);

  // optional double offset = 3;
  void clear_offset();
  static const int kOffsetFieldNumber = 3;
  double offset() const;
  void set_offset(double value);

  // @@protoc_insertion_point(class_scope:google.api.Distribution.BucketOptions.Linear)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double width_;
  double offset_;
  ::google::protobuf::int32 num_finite_buckets_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2fapi_2fdistribution_2eproto();
  friend void protobuf_AssignDesc_google_2fapi_2fdistribution_2eproto();
  friend void protobuf_ShutdownFile_google_2fapi_2fdistribution_2eproto();

  void InitAsDefaultInstance();
  static Distribution_BucketOptions_Linear* default_instance_;
};
// -------------------------------------------------------------------

class Distribution_BucketOptions_Exponential : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.api.Distribution.BucketOptions.Exponential) */ {
 public:
  Distribution_BucketOptions_Exponential();
  virtual ~Distribution_BucketOptions_Exponential();

  Distribution_BucketOptions_Exponential(const Distribution_BucketOptions_Exponential& from);

  inline Distribution_BucketOptions_Exponential& operator=(const Distribution_BucketOptions_Exponential& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Distribution_BucketOptions_Exponential& default_instance();

  void Swap(Distribution_BucketOptions_Exponential* other);

  // implements Message ----------------------------------------------

  inline Distribution_BucketOptions_Exponential* New() const { return New(NULL); }

  Distribution_BucketOptions_Exponential* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Distribution_BucketOptions_Exponential& from);
  void MergeFrom(const Distribution_BucketOptions_Exponential& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Distribution_BucketOptions_Exponential* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 num_finite_buckets = 1;
  void clear_num_finite_buckets();
  static const int kNumFiniteBucketsFieldNumber = 1;
  ::google::protobuf::int32 num_finite_buckets() const;
  void set_num_finite_buckets(::google::protobuf::int32 value);

  // optional double growth_factor = 2;
  void clear_growth_factor();
  static const int kGrowthFactorFieldNumber = 2;
  double growth_factor() const;
  void set_growth_factor(double value);

  // optional double scale = 3;
  void clear_scale();
  static const int kScaleFieldNumber = 3;
  double scale() const;
  void set_scale(double value);

  // @@protoc_insertion_point(class_scope:google.api.Distribution.BucketOptions.Exponential)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double growth_factor_;
  double scale_;
  ::google::protobuf::int32 num_finite_buckets_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2fapi_2fdistribution_2eproto();
  friend void protobuf_AssignDesc_google_2fapi_2fdistribution_2eproto();
  friend void protobuf_ShutdownFile_google_2fapi_2fdistribution_2eproto();

  void InitAsDefaultInstance();
  static Distribution_BucketOptions_Exponential* default_instance_;
};
// -------------------------------------------------------------------

class Distribution_BucketOptions_Explicit : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.api.Distribution.BucketOptions.Explicit) */ {
 public:
  Distribution_BucketOptions_Explicit();
  virtual ~Distribution_BucketOptions_Explicit();

  Distribution_BucketOptions_Explicit(const Distribution_BucketOptions_Explicit& from);

  inline Distribution_BucketOptions_Explicit& operator=(const Distribution_BucketOptions_Explicit& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Distribution_BucketOptions_Explicit& default_instance();

  void Swap(Distribution_BucketOptions_Explicit* other);

  // implements Message ----------------------------------------------

  inline Distribution_BucketOptions_Explicit* New() const { return New(NULL); }

  Distribution_BucketOptions_Explicit* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Distribution_BucketOptions_Explicit& from);
  void MergeFrom(const Distribution_BucketOptions_Explicit& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Distribution_BucketOptions_Explicit* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double bounds = 1;
  int bounds_size() const;
  void clear_bounds();
  static const int kBoundsFieldNumber = 1;
  double bounds(int index) const;
  void set_bounds(int index, double value);
  void add_bounds(double value);
  const ::google::protobuf::RepeatedField< double >&
      bounds() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_bounds();

  // @@protoc_insertion_point(class_scope:google.api.Distribution.BucketOptions.Explicit)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedField< double > bounds_;
  mutable int _bounds_cached_byte_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2fapi_2fdistribution_2eproto();
  friend void protobuf_AssignDesc_google_2fapi_2fdistribution_2eproto();
  friend void protobuf_ShutdownFile_google_2fapi_2fdistribution_2eproto();

  void InitAsDefaultInstance();
  static Distribution_BucketOptions_Explicit* default_instance_;
};
// -------------------------------------------------------------------

class Distribution_BucketOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.api.Distribution.BucketOptions) */ {
 public:
  Distribution_BucketOptions();
  virtual ~Distribution_BucketOptions();

  Distribution_BucketOptions(const Distribution_BucketOptions& from);

  inline Distribution_BucketOptions& operator=(const Distribution_BucketOptions& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Distribution_BucketOptions& default_instance();

  enum OptionsCase {
    kLinearBuckets = 1,
    kExponentialBuckets = 2,
    kExplicitBuckets = 3,
    OPTIONS_NOT_SET = 0,
  };

  void Swap(Distribution_BucketOptions* other);

  // implements Message ----------------------------------------------

  inline Distribution_BucketOptions* New() const { return New(NULL); }

  Distribution_BucketOptions* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Distribution_BucketOptions& from);
  void MergeFrom(const Distribution_BucketOptions& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Distribution_BucketOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Distribution_BucketOptions_Linear Linear;
  typedef Distribution_BucketOptions_Exponential Exponential;
  typedef Distribution_BucketOptions_Explicit Explicit;

  // accessors -------------------------------------------------------

  // optional .google.api.Distribution.BucketOptions.Linear linear_buckets = 1;
  bool has_linear_buckets() const;
  void clear_linear_buckets();
  static const int kLinearBucketsFieldNumber = 1;
  const ::google::api::Distribution_BucketOptions_Linear& linear_buckets() const;
  ::google::api::Distribution_BucketOptions_Linear* mutable_linear_buckets();
  ::google::api::Distribution_BucketOptions_Linear* release_linear_buckets();
  void set_allocated_linear_buckets(::google::api::Distribution_BucketOptions_Linear* linear_buckets);

  // optional .google.api.Distribution.BucketOptions.Exponential exponential_buckets = 2;
  bool has_exponential_buckets() const;
  void clear_exponential_buckets();
  static const int kExponentialBucketsFieldNumber = 2;
  const ::google::api::Distribution_BucketOptions_Exponential& exponential_buckets() const;
  ::google::api::Distribution_BucketOptions_Exponential* mutable_exponential_buckets();
  ::google::api::Distribution_BucketOptions_Exponential* release_exponential_buckets();
  void set_allocated_exponential_buckets(::google::api::Distribution_BucketOptions_Exponential* exponential_buckets);

  // optional .google.api.Distribution.BucketOptions.Explicit explicit_buckets = 3;
  bool has_explicit_buckets() const;
  void clear_explicit_buckets();
  static const int kExplicitBucketsFieldNumber = 3;
  const ::google::api::Distribution_BucketOptions_Explicit& explicit_buckets() const;
  ::google::api::Distribution_BucketOptions_Explicit* mutable_explicit_buckets();
  ::google::api::Distribution_BucketOptions_Explicit* release_explicit_buckets();
  void set_allocated_explicit_buckets(::google::api::Distribution_BucketOptions_Explicit* explicit_buckets);

  OptionsCase options_case() const;
  // @@protoc_insertion_point(class_scope:google.api.Distribution.BucketOptions)
 private:
  inline void set_has_linear_buckets();
  inline void set_has_exponential_buckets();
  inline void set_has_explicit_buckets();

  inline bool has_options() const;
  void clear_options();
  inline void clear_has_options();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  union OptionsUnion {
    OptionsUnion() {}
    ::google::api::Distribution_BucketOptions_Linear* linear_buckets_;
    ::google::api::Distribution_BucketOptions_Exponential* exponential_buckets_;
    ::google::api::Distribution_BucketOptions_Explicit* explicit_buckets_;
  } options_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_google_2fapi_2fdistribution_2eproto();
  friend void protobuf_AssignDesc_google_2fapi_2fdistribution_2eproto();
  friend void protobuf_ShutdownFile_google_2fapi_2fdistribution_2eproto();

  void InitAsDefaultInstance();
  static Distribution_BucketOptions* default_instance_;
};
// -------------------------------------------------------------------

class Distribution : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.api.Distribution) */ {
 public:
  Distribution();
  virtual ~Distribution();

  Distribution(const Distribution& from);

  inline Distribution& operator=(const Distribution& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Distribution& default_instance();

  void Swap(Distribution* other);

  // implements Message ----------------------------------------------

  inline Distribution* New() const { return New(NULL); }

  Distribution* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Distribution& from);
  void MergeFrom(const Distribution& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Distribution* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Distribution_Range Range;
  typedef Distribution_BucketOptions BucketOptions;

  // accessors -------------------------------------------------------

  // optional int64 count = 1;
  void clear_count();
  static const int kCountFieldNumber = 1;
  ::google::protobuf::int64 count() const;
  void set_count(::google::protobuf::int64 value);

  // optional double mean = 2;
  void clear_mean();
  static const int kMeanFieldNumber = 2;
  double mean() const;
  void set_mean(double value);

  // optional double sum_of_squared_deviation = 3;
  void clear_sum_of_squared_deviation();
  static const int kSumOfSquaredDeviationFieldNumber = 3;
  double sum_of_squared_deviation() const;
  void set_sum_of_squared_deviation(double value);

  // optional .google.api.Distribution.Range range = 4;
  bool has_range() const;
  void clear_range();
  static const int kRangeFieldNumber = 4;
  const ::google::api::Distribution_Range& range() const;
  ::google::api::Distribution_Range* mutable_range();
  ::google::api::Distribution_Range* release_range();
  void set_allocated_range(::google::api::Distribution_Range* range);

  // optional .google.api.Distribution.BucketOptions bucket_options = 6;
  bool has_bucket_options() const;
  void clear_bucket_options();
  static const int kBucketOptionsFieldNumber = 6;
  const ::google::api::Distribution_BucketOptions& bucket_options() const;
  ::google::api::Distribution_BucketOptions* mutable_bucket_options();
  ::google::api::Distribution_BucketOptions* release_bucket_options();
  void set_allocated_bucket_options(::google::api::Distribution_BucketOptions* bucket_options);

  // repeated int64 bucket_counts = 7;
  int bucket_counts_size() const;
  void clear_bucket_counts();
  static const int kBucketCountsFieldNumber = 7;
  ::google::protobuf::int64 bucket_counts(int index) const;
  void set_bucket_counts(int index, ::google::protobuf::int64 value);
  void add_bucket_counts(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      bucket_counts() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_bucket_counts();

  // @@protoc_insertion_point(class_scope:google.api.Distribution)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 count_;
  double mean_;
  double sum_of_squared_deviation_;
  ::google::api::Distribution_Range* range_;
  ::google::api::Distribution_BucketOptions* bucket_options_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > bucket_counts_;
  mutable int _bucket_counts_cached_byte_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2fapi_2fdistribution_2eproto();
  friend void protobuf_AssignDesc_google_2fapi_2fdistribution_2eproto();
  friend void protobuf_ShutdownFile_google_2fapi_2fdistribution_2eproto();

  void InitAsDefaultInstance();
  static Distribution* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Distribution_Range

// optional double min = 1;
inline void Distribution_Range::clear_min() {
  min_ = 0;
}
inline double Distribution_Range::min() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.Range.min)
  return min_;
}
inline void Distribution_Range::set_min(double value) {
  
  min_ = value;
  // @@protoc_insertion_point(field_set:google.api.Distribution.Range.min)
}

// optional double max = 2;
inline void Distribution_Range::clear_max() {
  max_ = 0;
}
inline double Distribution_Range::max() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.Range.max)
  return max_;
}
inline void Distribution_Range::set_max(double value) {
  
  max_ = value;
  // @@protoc_insertion_point(field_set:google.api.Distribution.Range.max)
}

// -------------------------------------------------------------------

// Distribution_BucketOptions_Linear

// optional int32 num_finite_buckets = 1;
inline void Distribution_BucketOptions_Linear::clear_num_finite_buckets() {
  num_finite_buckets_ = 0;
}
inline ::google::protobuf::int32 Distribution_BucketOptions_Linear::num_finite_buckets() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.BucketOptions.Linear.num_finite_buckets)
  return num_finite_buckets_;
}
inline void Distribution_BucketOptions_Linear::set_num_finite_buckets(::google::protobuf::int32 value) {
  
  num_finite_buckets_ = value;
  // @@protoc_insertion_point(field_set:google.api.Distribution.BucketOptions.Linear.num_finite_buckets)
}

// optional double width = 2;
inline void Distribution_BucketOptions_Linear::clear_width() {
  width_ = 0;
}
inline double Distribution_BucketOptions_Linear::width() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.BucketOptions.Linear.width)
  return width_;
}
inline void Distribution_BucketOptions_Linear::set_width(double value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:google.api.Distribution.BucketOptions.Linear.width)
}

// optional double offset = 3;
inline void Distribution_BucketOptions_Linear::clear_offset() {
  offset_ = 0;
}
inline double Distribution_BucketOptions_Linear::offset() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.BucketOptions.Linear.offset)
  return offset_;
}
inline void Distribution_BucketOptions_Linear::set_offset(double value) {
  
  offset_ = value;
  // @@protoc_insertion_point(field_set:google.api.Distribution.BucketOptions.Linear.offset)
}

// -------------------------------------------------------------------

// Distribution_BucketOptions_Exponential

// optional int32 num_finite_buckets = 1;
inline void Distribution_BucketOptions_Exponential::clear_num_finite_buckets() {
  num_finite_buckets_ = 0;
}
inline ::google::protobuf::int32 Distribution_BucketOptions_Exponential::num_finite_buckets() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.BucketOptions.Exponential.num_finite_buckets)
  return num_finite_buckets_;
}
inline void Distribution_BucketOptions_Exponential::set_num_finite_buckets(::google::protobuf::int32 value) {
  
  num_finite_buckets_ = value;
  // @@protoc_insertion_point(field_set:google.api.Distribution.BucketOptions.Exponential.num_finite_buckets)
}

// optional double growth_factor = 2;
inline void Distribution_BucketOptions_Exponential::clear_growth_factor() {
  growth_factor_ = 0;
}
inline double Distribution_BucketOptions_Exponential::growth_factor() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.BucketOptions.Exponential.growth_factor)
  return growth_factor_;
}
inline void Distribution_BucketOptions_Exponential::set_growth_factor(double value) {
  
  growth_factor_ = value;
  // @@protoc_insertion_point(field_set:google.api.Distribution.BucketOptions.Exponential.growth_factor)
}

// optional double scale = 3;
inline void Distribution_BucketOptions_Exponential::clear_scale() {
  scale_ = 0;
}
inline double Distribution_BucketOptions_Exponential::scale() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.BucketOptions.Exponential.scale)
  return scale_;
}
inline void Distribution_BucketOptions_Exponential::set_scale(double value) {
  
  scale_ = value;
  // @@protoc_insertion_point(field_set:google.api.Distribution.BucketOptions.Exponential.scale)
}

// -------------------------------------------------------------------

// Distribution_BucketOptions_Explicit

// repeated double bounds = 1;
inline int Distribution_BucketOptions_Explicit::bounds_size() const {
  return bounds_.size();
}
inline void Distribution_BucketOptions_Explicit::clear_bounds() {
  bounds_.Clear();
}
inline double Distribution_BucketOptions_Explicit::bounds(int index) const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.BucketOptions.Explicit.bounds)
  return bounds_.Get(index);
}
inline void Distribution_BucketOptions_Explicit::set_bounds(int index, double value) {
  bounds_.Set(index, value);
  // @@protoc_insertion_point(field_set:google.api.Distribution.BucketOptions.Explicit.bounds)
}
inline void Distribution_BucketOptions_Explicit::add_bounds(double value) {
  bounds_.Add(value);
  // @@protoc_insertion_point(field_add:google.api.Distribution.BucketOptions.Explicit.bounds)
}
inline const ::google::protobuf::RepeatedField< double >&
Distribution_BucketOptions_Explicit::bounds() const {
  // @@protoc_insertion_point(field_list:google.api.Distribution.BucketOptions.Explicit.bounds)
  return bounds_;
}
inline ::google::protobuf::RepeatedField< double >*
Distribution_BucketOptions_Explicit::mutable_bounds() {
  // @@protoc_insertion_point(field_mutable_list:google.api.Distribution.BucketOptions.Explicit.bounds)
  return &bounds_;
}

// -------------------------------------------------------------------

// Distribution_BucketOptions

// optional .google.api.Distribution.BucketOptions.Linear linear_buckets = 1;
inline bool Distribution_BucketOptions::has_linear_buckets() const {
  return options_case() == kLinearBuckets;
}
inline void Distribution_BucketOptions::set_has_linear_buckets() {
  _oneof_case_[0] = kLinearBuckets;
}
inline void Distribution_BucketOptions::clear_linear_buckets() {
  if (has_linear_buckets()) {
    delete options_.linear_buckets_;
    clear_has_options();
  }
}
inline  const ::google::api::Distribution_BucketOptions_Linear& Distribution_BucketOptions::linear_buckets() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.BucketOptions.linear_buckets)
  return has_linear_buckets()
      ? *options_.linear_buckets_
      : ::google::api::Distribution_BucketOptions_Linear::default_instance();
}
inline ::google::api::Distribution_BucketOptions_Linear* Distribution_BucketOptions::mutable_linear_buckets() {
  if (!has_linear_buckets()) {
    clear_options();
    set_has_linear_buckets();
    options_.linear_buckets_ = new ::google::api::Distribution_BucketOptions_Linear;
  }
  // @@protoc_insertion_point(field_mutable:google.api.Distribution.BucketOptions.linear_buckets)
  return options_.linear_buckets_;
}
inline ::google::api::Distribution_BucketOptions_Linear* Distribution_BucketOptions::release_linear_buckets() {
  // @@protoc_insertion_point(field_release:google.api.Distribution.BucketOptions.linear_buckets)
  if (has_linear_buckets()) {
    clear_has_options();
    ::google::api::Distribution_BucketOptions_Linear* temp = options_.linear_buckets_;
    options_.linear_buckets_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Distribution_BucketOptions::set_allocated_linear_buckets(::google::api::Distribution_BucketOptions_Linear* linear_buckets) {
  clear_options();
  if (linear_buckets) {
    set_has_linear_buckets();
    options_.linear_buckets_ = linear_buckets;
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.Distribution.BucketOptions.linear_buckets)
}

// optional .google.api.Distribution.BucketOptions.Exponential exponential_buckets = 2;
inline bool Distribution_BucketOptions::has_exponential_buckets() const {
  return options_case() == kExponentialBuckets;
}
inline void Distribution_BucketOptions::set_has_exponential_buckets() {
  _oneof_case_[0] = kExponentialBuckets;
}
inline void Distribution_BucketOptions::clear_exponential_buckets() {
  if (has_exponential_buckets()) {
    delete options_.exponential_buckets_;
    clear_has_options();
  }
}
inline  const ::google::api::Distribution_BucketOptions_Exponential& Distribution_BucketOptions::exponential_buckets() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.BucketOptions.exponential_buckets)
  return has_exponential_buckets()
      ? *options_.exponential_buckets_
      : ::google::api::Distribution_BucketOptions_Exponential::default_instance();
}
inline ::google::api::Distribution_BucketOptions_Exponential* Distribution_BucketOptions::mutable_exponential_buckets() {
  if (!has_exponential_buckets()) {
    clear_options();
    set_has_exponential_buckets();
    options_.exponential_buckets_ = new ::google::api::Distribution_BucketOptions_Exponential;
  }
  // @@protoc_insertion_point(field_mutable:google.api.Distribution.BucketOptions.exponential_buckets)
  return options_.exponential_buckets_;
}
inline ::google::api::Distribution_BucketOptions_Exponential* Distribution_BucketOptions::release_exponential_buckets() {
  // @@protoc_insertion_point(field_release:google.api.Distribution.BucketOptions.exponential_buckets)
  if (has_exponential_buckets()) {
    clear_has_options();
    ::google::api::Distribution_BucketOptions_Exponential* temp = options_.exponential_buckets_;
    options_.exponential_buckets_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Distribution_BucketOptions::set_allocated_exponential_buckets(::google::api::Distribution_BucketOptions_Exponential* exponential_buckets) {
  clear_options();
  if (exponential_buckets) {
    set_has_exponential_buckets();
    options_.exponential_buckets_ = exponential_buckets;
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.Distribution.BucketOptions.exponential_buckets)
}

// optional .google.api.Distribution.BucketOptions.Explicit explicit_buckets = 3;
inline bool Distribution_BucketOptions::has_explicit_buckets() const {
  return options_case() == kExplicitBuckets;
}
inline void Distribution_BucketOptions::set_has_explicit_buckets() {
  _oneof_case_[0] = kExplicitBuckets;
}
inline void Distribution_BucketOptions::clear_explicit_buckets() {
  if (has_explicit_buckets()) {
    delete options_.explicit_buckets_;
    clear_has_options();
  }
}
inline  const ::google::api::Distribution_BucketOptions_Explicit& Distribution_BucketOptions::explicit_buckets() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.BucketOptions.explicit_buckets)
  return has_explicit_buckets()
      ? *options_.explicit_buckets_
      : ::google::api::Distribution_BucketOptions_Explicit::default_instance();
}
inline ::google::api::Distribution_BucketOptions_Explicit* Distribution_BucketOptions::mutable_explicit_buckets() {
  if (!has_explicit_buckets()) {
    clear_options();
    set_has_explicit_buckets();
    options_.explicit_buckets_ = new ::google::api::Distribution_BucketOptions_Explicit;
  }
  // @@protoc_insertion_point(field_mutable:google.api.Distribution.BucketOptions.explicit_buckets)
  return options_.explicit_buckets_;
}
inline ::google::api::Distribution_BucketOptions_Explicit* Distribution_BucketOptions::release_explicit_buckets() {
  // @@protoc_insertion_point(field_release:google.api.Distribution.BucketOptions.explicit_buckets)
  if (has_explicit_buckets()) {
    clear_has_options();
    ::google::api::Distribution_BucketOptions_Explicit* temp = options_.explicit_buckets_;
    options_.explicit_buckets_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Distribution_BucketOptions::set_allocated_explicit_buckets(::google::api::Distribution_BucketOptions_Explicit* explicit_buckets) {
  clear_options();
  if (explicit_buckets) {
    set_has_explicit_buckets();
    options_.explicit_buckets_ = explicit_buckets;
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.Distribution.BucketOptions.explicit_buckets)
}

inline bool Distribution_BucketOptions::has_options() const {
  return options_case() != OPTIONS_NOT_SET;
}
inline void Distribution_BucketOptions::clear_has_options() {
  _oneof_case_[0] = OPTIONS_NOT_SET;
}
inline Distribution_BucketOptions::OptionsCase Distribution_BucketOptions::options_case() const {
  return Distribution_BucketOptions::OptionsCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Distribution

// optional int64 count = 1;
inline void Distribution::clear_count() {
  count_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Distribution::count() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.count)
  return count_;
}
inline void Distribution::set_count(::google::protobuf::int64 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:google.api.Distribution.count)
}

// optional double mean = 2;
inline void Distribution::clear_mean() {
  mean_ = 0;
}
inline double Distribution::mean() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.mean)
  return mean_;
}
inline void Distribution::set_mean(double value) {
  
  mean_ = value;
  // @@protoc_insertion_point(field_set:google.api.Distribution.mean)
}

// optional double sum_of_squared_deviation = 3;
inline void Distribution::clear_sum_of_squared_deviation() {
  sum_of_squared_deviation_ = 0;
}
inline double Distribution::sum_of_squared_deviation() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.sum_of_squared_deviation)
  return sum_of_squared_deviation_;
}
inline void Distribution::set_sum_of_squared_deviation(double value) {
  
  sum_of_squared_deviation_ = value;
  // @@protoc_insertion_point(field_set:google.api.Distribution.sum_of_squared_deviation)
}

// optional .google.api.Distribution.Range range = 4;
inline bool Distribution::has_range() const {
  return !_is_default_instance_ && range_ != NULL;
}
inline void Distribution::clear_range() {
  if (GetArenaNoVirtual() == NULL && range_ != NULL) delete range_;
  range_ = NULL;
}
inline const ::google::api::Distribution_Range& Distribution::range() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.range)
  return range_ != NULL ? *range_ : *default_instance_->range_;
}
inline ::google::api::Distribution_Range* Distribution::mutable_range() {
  
  if (range_ == NULL) {
    range_ = new ::google::api::Distribution_Range;
  }
  // @@protoc_insertion_point(field_mutable:google.api.Distribution.range)
  return range_;
}
inline ::google::api::Distribution_Range* Distribution::release_range() {
  // @@protoc_insertion_point(field_release:google.api.Distribution.range)
  
  ::google::api::Distribution_Range* temp = range_;
  range_ = NULL;
  return temp;
}
inline void Distribution::set_allocated_range(::google::api::Distribution_Range* range) {
  delete range_;
  range_ = range;
  if (range) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.Distribution.range)
}

// optional .google.api.Distribution.BucketOptions bucket_options = 6;
inline bool Distribution::has_bucket_options() const {
  return !_is_default_instance_ && bucket_options_ != NULL;
}
inline void Distribution::clear_bucket_options() {
  if (GetArenaNoVirtual() == NULL && bucket_options_ != NULL) delete bucket_options_;
  bucket_options_ = NULL;
}
inline const ::google::api::Distribution_BucketOptions& Distribution::bucket_options() const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.bucket_options)
  return bucket_options_ != NULL ? *bucket_options_ : *default_instance_->bucket_options_;
}
inline ::google::api::Distribution_BucketOptions* Distribution::mutable_bucket_options() {
  
  if (bucket_options_ == NULL) {
    bucket_options_ = new ::google::api::Distribution_BucketOptions;
  }
  // @@protoc_insertion_point(field_mutable:google.api.Distribution.bucket_options)
  return bucket_options_;
}
inline ::google::api::Distribution_BucketOptions* Distribution::release_bucket_options() {
  // @@protoc_insertion_point(field_release:google.api.Distribution.bucket_options)
  
  ::google::api::Distribution_BucketOptions* temp = bucket_options_;
  bucket_options_ = NULL;
  return temp;
}
inline void Distribution::set_allocated_bucket_options(::google::api::Distribution_BucketOptions* bucket_options) {
  delete bucket_options_;
  bucket_options_ = bucket_options;
  if (bucket_options) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.Distribution.bucket_options)
}

// repeated int64 bucket_counts = 7;
inline int Distribution::bucket_counts_size() const {
  return bucket_counts_.size();
}
inline void Distribution::clear_bucket_counts() {
  bucket_counts_.Clear();
}
inline ::google::protobuf::int64 Distribution::bucket_counts(int index) const {
  // @@protoc_insertion_point(field_get:google.api.Distribution.bucket_counts)
  return bucket_counts_.Get(index);
}
inline void Distribution::set_bucket_counts(int index, ::google::protobuf::int64 value) {
  bucket_counts_.Set(index, value);
  // @@protoc_insertion_point(field_set:google.api.Distribution.bucket_counts)
}
inline void Distribution::add_bucket_counts(::google::protobuf::int64 value) {
  bucket_counts_.Add(value);
  // @@protoc_insertion_point(field_add:google.api.Distribution.bucket_counts)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
Distribution::bucket_counts() const {
  // @@protoc_insertion_point(field_list:google.api.Distribution.bucket_counts)
  return bucket_counts_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
Distribution::mutable_bucket_counts() {
  // @@protoc_insertion_point(field_mutable_list:google.api.Distribution.bucket_counts)
  return &bucket_counts_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace api
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_google_2fapi_2fdistribution_2eproto__INCLUDED
