// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/logging/v2/logging_metrics.proto

#ifndef PROTOBUF_google_2flogging_2fv2_2flogging_5fmetrics_2eproto__INCLUDED
#define PROTOBUF_google_2flogging_2fv2_2flogging_5fmetrics_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "google/api/annotations.pb.h"
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)

namespace google {
namespace logging {
namespace v2 {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
void protobuf_AssignDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
void protobuf_ShutdownFile_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();

class CreateLogMetricRequest;
class DeleteLogMetricRequest;
class GetLogMetricRequest;
class ListLogMetricsRequest;
class ListLogMetricsResponse;
class LogMetric;
class UpdateLogMetricRequest;

enum LogMetric_ApiVersion {
  LogMetric_ApiVersion_V2 = 0,
  LogMetric_ApiVersion_V1 = 1,
  LogMetric_ApiVersion_LogMetric_ApiVersion_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  LogMetric_ApiVersion_LogMetric_ApiVersion_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool LogMetric_ApiVersion_IsValid(int value);
const LogMetric_ApiVersion LogMetric_ApiVersion_ApiVersion_MIN = LogMetric_ApiVersion_V2;
const LogMetric_ApiVersion LogMetric_ApiVersion_ApiVersion_MAX = LogMetric_ApiVersion_V1;
const int LogMetric_ApiVersion_ApiVersion_ARRAYSIZE = LogMetric_ApiVersion_ApiVersion_MAX + 1;

const ::google::protobuf::EnumDescriptor* LogMetric_ApiVersion_descriptor();
inline const ::std::string& LogMetric_ApiVersion_Name(LogMetric_ApiVersion value) {
  return ::google::protobuf::internal::NameOfEnum(
    LogMetric_ApiVersion_descriptor(), value);
}
inline bool LogMetric_ApiVersion_Parse(
    const ::std::string& name, LogMetric_ApiVersion* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LogMetric_ApiVersion>(
    LogMetric_ApiVersion_descriptor(), name, value);
}
// ===================================================================

class LogMetric : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.logging.v2.LogMetric) */ {
 public:
  LogMetric();
  virtual ~LogMetric();

  LogMetric(const LogMetric& from);

  inline LogMetric& operator=(const LogMetric& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogMetric& default_instance();

  void Swap(LogMetric* other);

  // implements Message ----------------------------------------------

  inline LogMetric* New() const { return New(NULL); }

  LogMetric* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogMetric& from);
  void MergeFrom(const LogMetric& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LogMetric* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef LogMetric_ApiVersion ApiVersion;
  static const ApiVersion V2 =
    LogMetric_ApiVersion_V2;
  static const ApiVersion V1 =
    LogMetric_ApiVersion_V1;
  static inline bool ApiVersion_IsValid(int value) {
    return LogMetric_ApiVersion_IsValid(value);
  }
  static const ApiVersion ApiVersion_MIN =
    LogMetric_ApiVersion_ApiVersion_MIN;
  static const ApiVersion ApiVersion_MAX =
    LogMetric_ApiVersion_ApiVersion_MAX;
  static const int ApiVersion_ARRAYSIZE =
    LogMetric_ApiVersion_ApiVersion_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ApiVersion_descriptor() {
    return LogMetric_ApiVersion_descriptor();
  }
  static inline const ::std::string& ApiVersion_Name(ApiVersion value) {
    return LogMetric_ApiVersion_Name(value);
  }
  static inline bool ApiVersion_Parse(const ::std::string& name,
      ApiVersion* value) {
    return LogMetric_ApiVersion_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string description = 2;
  void clear_description();
  static const int kDescriptionFieldNumber = 2;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // optional string filter = 3;
  void clear_filter();
  static const int kFilterFieldNumber = 3;
  const ::std::string& filter() const;
  void set_filter(const ::std::string& value);
  void set_filter(const char* value);
  void set_filter(const char* value, size_t size);
  ::std::string* mutable_filter();
  ::std::string* release_filter();
  void set_allocated_filter(::std::string* filter);

  // optional .google.logging.v2.LogMetric.ApiVersion version = 4;
  void clear_version();
  static const int kVersionFieldNumber = 4;
  ::google::logging::v2::LogMetric_ApiVersion version() const;
  void set_version(::google::logging::v2::LogMetric_ApiVersion value);

  // @@protoc_insertion_point(class_scope:google.logging.v2.LogMetric)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::internal::ArenaStringPtr filter_;
  int version_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_AssignDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_ShutdownFile_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();

  void InitAsDefaultInstance();
  static LogMetric* default_instance_;
};
// -------------------------------------------------------------------

class ListLogMetricsRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.logging.v2.ListLogMetricsRequest) */ {
 public:
  ListLogMetricsRequest();
  virtual ~ListLogMetricsRequest();

  ListLogMetricsRequest(const ListLogMetricsRequest& from);

  inline ListLogMetricsRequest& operator=(const ListLogMetricsRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ListLogMetricsRequest& default_instance();

  void Swap(ListLogMetricsRequest* other);

  // implements Message ----------------------------------------------

  inline ListLogMetricsRequest* New() const { return New(NULL); }

  ListLogMetricsRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListLogMetricsRequest& from);
  void MergeFrom(const ListLogMetricsRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListLogMetricsRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string parent = 1;
  void clear_parent();
  static const int kParentFieldNumber = 1;
  const ::std::string& parent() const;
  void set_parent(const ::std::string& value);
  void set_parent(const char* value);
  void set_parent(const char* value, size_t size);
  ::std::string* mutable_parent();
  ::std::string* release_parent();
  void set_allocated_parent(::std::string* parent);

  // optional string page_token = 2;
  void clear_page_token();
  static const int kPageTokenFieldNumber = 2;
  const ::std::string& page_token() const;
  void set_page_token(const ::std::string& value);
  void set_page_token(const char* value);
  void set_page_token(const char* value, size_t size);
  ::std::string* mutable_page_token();
  ::std::string* release_page_token();
  void set_allocated_page_token(::std::string* page_token);

  // optional int32 page_size = 3;
  void clear_page_size();
  static const int kPageSizeFieldNumber = 3;
  ::google::protobuf::int32 page_size() const;
  void set_page_size(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:google.logging.v2.ListLogMetricsRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr parent_;
  ::google::protobuf::internal::ArenaStringPtr page_token_;
  ::google::protobuf::int32 page_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_AssignDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_ShutdownFile_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();

  void InitAsDefaultInstance();
  static ListLogMetricsRequest* default_instance_;
};
// -------------------------------------------------------------------

class ListLogMetricsResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.logging.v2.ListLogMetricsResponse) */ {
 public:
  ListLogMetricsResponse();
  virtual ~ListLogMetricsResponse();

  ListLogMetricsResponse(const ListLogMetricsResponse& from);

  inline ListLogMetricsResponse& operator=(const ListLogMetricsResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ListLogMetricsResponse& default_instance();

  void Swap(ListLogMetricsResponse* other);

  // implements Message ----------------------------------------------

  inline ListLogMetricsResponse* New() const { return New(NULL); }

  ListLogMetricsResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListLogMetricsResponse& from);
  void MergeFrom(const ListLogMetricsResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListLogMetricsResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .google.logging.v2.LogMetric metrics = 1;
  int metrics_size() const;
  void clear_metrics();
  static const int kMetricsFieldNumber = 1;
  const ::google::logging::v2::LogMetric& metrics(int index) const;
  ::google::logging::v2::LogMetric* mutable_metrics(int index);
  ::google::logging::v2::LogMetric* add_metrics();
  ::google::protobuf::RepeatedPtrField< ::google::logging::v2::LogMetric >*
      mutable_metrics();
  const ::google::protobuf::RepeatedPtrField< ::google::logging::v2::LogMetric >&
      metrics() const;

  // optional string next_page_token = 2;
  void clear_next_page_token();
  static const int kNextPageTokenFieldNumber = 2;
  const ::std::string& next_page_token() const;
  void set_next_page_token(const ::std::string& value);
  void set_next_page_token(const char* value);
  void set_next_page_token(const char* value, size_t size);
  ::std::string* mutable_next_page_token();
  ::std::string* release_next_page_token();
  void set_allocated_next_page_token(::std::string* next_page_token);

  // @@protoc_insertion_point(class_scope:google.logging.v2.ListLogMetricsResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::google::logging::v2::LogMetric > metrics_;
  ::google::protobuf::internal::ArenaStringPtr next_page_token_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_AssignDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_ShutdownFile_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();

  void InitAsDefaultInstance();
  static ListLogMetricsResponse* default_instance_;
};
// -------------------------------------------------------------------

class GetLogMetricRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.logging.v2.GetLogMetricRequest) */ {
 public:
  GetLogMetricRequest();
  virtual ~GetLogMetricRequest();

  GetLogMetricRequest(const GetLogMetricRequest& from);

  inline GetLogMetricRequest& operator=(const GetLogMetricRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetLogMetricRequest& default_instance();

  void Swap(GetLogMetricRequest* other);

  // implements Message ----------------------------------------------

  inline GetLogMetricRequest* New() const { return New(NULL); }

  GetLogMetricRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetLogMetricRequest& from);
  void MergeFrom(const GetLogMetricRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetLogMetricRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string metric_name = 1;
  void clear_metric_name();
  static const int kMetricNameFieldNumber = 1;
  const ::std::string& metric_name() const;
  void set_metric_name(const ::std::string& value);
  void set_metric_name(const char* value);
  void set_metric_name(const char* value, size_t size);
  ::std::string* mutable_metric_name();
  ::std::string* release_metric_name();
  void set_allocated_metric_name(::std::string* metric_name);

  // @@protoc_insertion_point(class_scope:google.logging.v2.GetLogMetricRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr metric_name_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_AssignDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_ShutdownFile_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();

  void InitAsDefaultInstance();
  static GetLogMetricRequest* default_instance_;
};
// -------------------------------------------------------------------

class CreateLogMetricRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.logging.v2.CreateLogMetricRequest) */ {
 public:
  CreateLogMetricRequest();
  virtual ~CreateLogMetricRequest();

  CreateLogMetricRequest(const CreateLogMetricRequest& from);

  inline CreateLogMetricRequest& operator=(const CreateLogMetricRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateLogMetricRequest& default_instance();

  void Swap(CreateLogMetricRequest* other);

  // implements Message ----------------------------------------------

  inline CreateLogMetricRequest* New() const { return New(NULL); }

  CreateLogMetricRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CreateLogMetricRequest& from);
  void MergeFrom(const CreateLogMetricRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CreateLogMetricRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string parent = 1;
  void clear_parent();
  static const int kParentFieldNumber = 1;
  const ::std::string& parent() const;
  void set_parent(const ::std::string& value);
  void set_parent(const char* value);
  void set_parent(const char* value, size_t size);
  ::std::string* mutable_parent();
  ::std::string* release_parent();
  void set_allocated_parent(::std::string* parent);

  // optional .google.logging.v2.LogMetric metric = 2;
  bool has_metric() const;
  void clear_metric();
  static const int kMetricFieldNumber = 2;
  const ::google::logging::v2::LogMetric& metric() const;
  ::google::logging::v2::LogMetric* mutable_metric();
  ::google::logging::v2::LogMetric* release_metric();
  void set_allocated_metric(::google::logging::v2::LogMetric* metric);

  // @@protoc_insertion_point(class_scope:google.logging.v2.CreateLogMetricRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr parent_;
  ::google::logging::v2::LogMetric* metric_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_AssignDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_ShutdownFile_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();

  void InitAsDefaultInstance();
  static CreateLogMetricRequest* default_instance_;
};
// -------------------------------------------------------------------

class UpdateLogMetricRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.logging.v2.UpdateLogMetricRequest) */ {
 public:
  UpdateLogMetricRequest();
  virtual ~UpdateLogMetricRequest();

  UpdateLogMetricRequest(const UpdateLogMetricRequest& from);

  inline UpdateLogMetricRequest& operator=(const UpdateLogMetricRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateLogMetricRequest& default_instance();

  void Swap(UpdateLogMetricRequest* other);

  // implements Message ----------------------------------------------

  inline UpdateLogMetricRequest* New() const { return New(NULL); }

  UpdateLogMetricRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateLogMetricRequest& from);
  void MergeFrom(const UpdateLogMetricRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateLogMetricRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string metric_name = 1;
  void clear_metric_name();
  static const int kMetricNameFieldNumber = 1;
  const ::std::string& metric_name() const;
  void set_metric_name(const ::std::string& value);
  void set_metric_name(const char* value);
  void set_metric_name(const char* value, size_t size);
  ::std::string* mutable_metric_name();
  ::std::string* release_metric_name();
  void set_allocated_metric_name(::std::string* metric_name);

  // optional .google.logging.v2.LogMetric metric = 2;
  bool has_metric() const;
  void clear_metric();
  static const int kMetricFieldNumber = 2;
  const ::google::logging::v2::LogMetric& metric() const;
  ::google::logging::v2::LogMetric* mutable_metric();
  ::google::logging::v2::LogMetric* release_metric();
  void set_allocated_metric(::google::logging::v2::LogMetric* metric);

  // @@protoc_insertion_point(class_scope:google.logging.v2.UpdateLogMetricRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr metric_name_;
  ::google::logging::v2::LogMetric* metric_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_AssignDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_ShutdownFile_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();

  void InitAsDefaultInstance();
  static UpdateLogMetricRequest* default_instance_;
};
// -------------------------------------------------------------------

class DeleteLogMetricRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.logging.v2.DeleteLogMetricRequest) */ {
 public:
  DeleteLogMetricRequest();
  virtual ~DeleteLogMetricRequest();

  DeleteLogMetricRequest(const DeleteLogMetricRequest& from);

  inline DeleteLogMetricRequest& operator=(const DeleteLogMetricRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteLogMetricRequest& default_instance();

  void Swap(DeleteLogMetricRequest* other);

  // implements Message ----------------------------------------------

  inline DeleteLogMetricRequest* New() const { return New(NULL); }

  DeleteLogMetricRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeleteLogMetricRequest& from);
  void MergeFrom(const DeleteLogMetricRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DeleteLogMetricRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string metric_name = 1;
  void clear_metric_name();
  static const int kMetricNameFieldNumber = 1;
  const ::std::string& metric_name() const;
  void set_metric_name(const ::std::string& value);
  void set_metric_name(const char* value);
  void set_metric_name(const char* value, size_t size);
  ::std::string* mutable_metric_name();
  ::std::string* release_metric_name();
  void set_allocated_metric_name(::std::string* metric_name);

  // @@protoc_insertion_point(class_scope:google.logging.v2.DeleteLogMetricRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr metric_name_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_AssignDesc_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();
  friend void protobuf_ShutdownFile_google_2flogging_2fv2_2flogging_5fmetrics_2eproto();

  void InitAsDefaultInstance();
  static DeleteLogMetricRequest* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LogMetric

// optional string name = 1;
inline void LogMetric::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LogMetric::name() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.LogMetric.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogMetric::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.logging.v2.LogMetric.name)
}
inline void LogMetric::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.logging.v2.LogMetric.name)
}
inline void LogMetric::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.logging.v2.LogMetric.name)
}
inline ::std::string* LogMetric::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:google.logging.v2.LogMetric.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LogMetric::release_name() {
  // @@protoc_insertion_point(field_release:google.logging.v2.LogMetric.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogMetric::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.LogMetric.name)
}

// optional string description = 2;
inline void LogMetric::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LogMetric::description() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.LogMetric.description)
  return description_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogMetric::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.logging.v2.LogMetric.description)
}
inline void LogMetric::set_description(const char* value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.logging.v2.LogMetric.description)
}
inline void LogMetric::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.logging.v2.LogMetric.description)
}
inline ::std::string* LogMetric::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:google.logging.v2.LogMetric.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LogMetric::release_description() {
  // @@protoc_insertion_point(field_release:google.logging.v2.LogMetric.description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogMetric::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.LogMetric.description)
}

// optional string filter = 3;
inline void LogMetric::clear_filter() {
  filter_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LogMetric::filter() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.LogMetric.filter)
  return filter_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogMetric::set_filter(const ::std::string& value) {
  
  filter_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.logging.v2.LogMetric.filter)
}
inline void LogMetric::set_filter(const char* value) {
  
  filter_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.logging.v2.LogMetric.filter)
}
inline void LogMetric::set_filter(const char* value, size_t size) {
  
  filter_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.logging.v2.LogMetric.filter)
}
inline ::std::string* LogMetric::mutable_filter() {
  
  // @@protoc_insertion_point(field_mutable:google.logging.v2.LogMetric.filter)
  return filter_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LogMetric::release_filter() {
  // @@protoc_insertion_point(field_release:google.logging.v2.LogMetric.filter)
  
  return filter_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogMetric::set_allocated_filter(::std::string* filter) {
  if (filter != NULL) {
    
  } else {
    
  }
  filter_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filter);
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.LogMetric.filter)
}

// optional .google.logging.v2.LogMetric.ApiVersion version = 4;
inline void LogMetric::clear_version() {
  version_ = 0;
}
inline ::google::logging::v2::LogMetric_ApiVersion LogMetric::version() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.LogMetric.version)
  return static_cast< ::google::logging::v2::LogMetric_ApiVersion >(version_);
}
inline void LogMetric::set_version(::google::logging::v2::LogMetric_ApiVersion value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:google.logging.v2.LogMetric.version)
}

// -------------------------------------------------------------------

// ListLogMetricsRequest

// optional string parent = 1;
inline void ListLogMetricsRequest::clear_parent() {
  parent_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ListLogMetricsRequest::parent() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.ListLogMetricsRequest.parent)
  return parent_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ListLogMetricsRequest::set_parent(const ::std::string& value) {
  
  parent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.logging.v2.ListLogMetricsRequest.parent)
}
inline void ListLogMetricsRequest::set_parent(const char* value) {
  
  parent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.logging.v2.ListLogMetricsRequest.parent)
}
inline void ListLogMetricsRequest::set_parent(const char* value, size_t size) {
  
  parent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.logging.v2.ListLogMetricsRequest.parent)
}
inline ::std::string* ListLogMetricsRequest::mutable_parent() {
  
  // @@protoc_insertion_point(field_mutable:google.logging.v2.ListLogMetricsRequest.parent)
  return parent_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ListLogMetricsRequest::release_parent() {
  // @@protoc_insertion_point(field_release:google.logging.v2.ListLogMetricsRequest.parent)
  
  return parent_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ListLogMetricsRequest::set_allocated_parent(::std::string* parent) {
  if (parent != NULL) {
    
  } else {
    
  }
  parent_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), parent);
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.ListLogMetricsRequest.parent)
}

// optional string page_token = 2;
inline void ListLogMetricsRequest::clear_page_token() {
  page_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ListLogMetricsRequest::page_token() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.ListLogMetricsRequest.page_token)
  return page_token_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ListLogMetricsRequest::set_page_token(const ::std::string& value) {
  
  page_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.logging.v2.ListLogMetricsRequest.page_token)
}
inline void ListLogMetricsRequest::set_page_token(const char* value) {
  
  page_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.logging.v2.ListLogMetricsRequest.page_token)
}
inline void ListLogMetricsRequest::set_page_token(const char* value, size_t size) {
  
  page_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.logging.v2.ListLogMetricsRequest.page_token)
}
inline ::std::string* ListLogMetricsRequest::mutable_page_token() {
  
  // @@protoc_insertion_point(field_mutable:google.logging.v2.ListLogMetricsRequest.page_token)
  return page_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ListLogMetricsRequest::release_page_token() {
  // @@protoc_insertion_point(field_release:google.logging.v2.ListLogMetricsRequest.page_token)
  
  return page_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ListLogMetricsRequest::set_allocated_page_token(::std::string* page_token) {
  if (page_token != NULL) {
    
  } else {
    
  }
  page_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), page_token);
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.ListLogMetricsRequest.page_token)
}

// optional int32 page_size = 3;
inline void ListLogMetricsRequest::clear_page_size() {
  page_size_ = 0;
}
inline ::google::protobuf::int32 ListLogMetricsRequest::page_size() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.ListLogMetricsRequest.page_size)
  return page_size_;
}
inline void ListLogMetricsRequest::set_page_size(::google::protobuf::int32 value) {
  
  page_size_ = value;
  // @@protoc_insertion_point(field_set:google.logging.v2.ListLogMetricsRequest.page_size)
}

// -------------------------------------------------------------------

// ListLogMetricsResponse

// repeated .google.logging.v2.LogMetric metrics = 1;
inline int ListLogMetricsResponse::metrics_size() const {
  return metrics_.size();
}
inline void ListLogMetricsResponse::clear_metrics() {
  metrics_.Clear();
}
inline const ::google::logging::v2::LogMetric& ListLogMetricsResponse::metrics(int index) const {
  // @@protoc_insertion_point(field_get:google.logging.v2.ListLogMetricsResponse.metrics)
  return metrics_.Get(index);
}
inline ::google::logging::v2::LogMetric* ListLogMetricsResponse::mutable_metrics(int index) {
  // @@protoc_insertion_point(field_mutable:google.logging.v2.ListLogMetricsResponse.metrics)
  return metrics_.Mutable(index);
}
inline ::google::logging::v2::LogMetric* ListLogMetricsResponse::add_metrics() {
  // @@protoc_insertion_point(field_add:google.logging.v2.ListLogMetricsResponse.metrics)
  return metrics_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::google::logging::v2::LogMetric >*
ListLogMetricsResponse::mutable_metrics() {
  // @@protoc_insertion_point(field_mutable_list:google.logging.v2.ListLogMetricsResponse.metrics)
  return &metrics_;
}
inline const ::google::protobuf::RepeatedPtrField< ::google::logging::v2::LogMetric >&
ListLogMetricsResponse::metrics() const {
  // @@protoc_insertion_point(field_list:google.logging.v2.ListLogMetricsResponse.metrics)
  return metrics_;
}

// optional string next_page_token = 2;
inline void ListLogMetricsResponse::clear_next_page_token() {
  next_page_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ListLogMetricsResponse::next_page_token() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.ListLogMetricsResponse.next_page_token)
  return next_page_token_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ListLogMetricsResponse::set_next_page_token(const ::std::string& value) {
  
  next_page_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.logging.v2.ListLogMetricsResponse.next_page_token)
}
inline void ListLogMetricsResponse::set_next_page_token(const char* value) {
  
  next_page_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.logging.v2.ListLogMetricsResponse.next_page_token)
}
inline void ListLogMetricsResponse::set_next_page_token(const char* value, size_t size) {
  
  next_page_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.logging.v2.ListLogMetricsResponse.next_page_token)
}
inline ::std::string* ListLogMetricsResponse::mutable_next_page_token() {
  
  // @@protoc_insertion_point(field_mutable:google.logging.v2.ListLogMetricsResponse.next_page_token)
  return next_page_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ListLogMetricsResponse::release_next_page_token() {
  // @@protoc_insertion_point(field_release:google.logging.v2.ListLogMetricsResponse.next_page_token)
  
  return next_page_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ListLogMetricsResponse::set_allocated_next_page_token(::std::string* next_page_token) {
  if (next_page_token != NULL) {
    
  } else {
    
  }
  next_page_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), next_page_token);
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.ListLogMetricsResponse.next_page_token)
}

// -------------------------------------------------------------------

// GetLogMetricRequest

// optional string metric_name = 1;
inline void GetLogMetricRequest::clear_metric_name() {
  metric_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetLogMetricRequest::metric_name() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.GetLogMetricRequest.metric_name)
  return metric_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetLogMetricRequest::set_metric_name(const ::std::string& value) {
  
  metric_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.logging.v2.GetLogMetricRequest.metric_name)
}
inline void GetLogMetricRequest::set_metric_name(const char* value) {
  
  metric_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.logging.v2.GetLogMetricRequest.metric_name)
}
inline void GetLogMetricRequest::set_metric_name(const char* value, size_t size) {
  
  metric_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.logging.v2.GetLogMetricRequest.metric_name)
}
inline ::std::string* GetLogMetricRequest::mutable_metric_name() {
  
  // @@protoc_insertion_point(field_mutable:google.logging.v2.GetLogMetricRequest.metric_name)
  return metric_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetLogMetricRequest::release_metric_name() {
  // @@protoc_insertion_point(field_release:google.logging.v2.GetLogMetricRequest.metric_name)
  
  return metric_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetLogMetricRequest::set_allocated_metric_name(::std::string* metric_name) {
  if (metric_name != NULL) {
    
  } else {
    
  }
  metric_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), metric_name);
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.GetLogMetricRequest.metric_name)
}

// -------------------------------------------------------------------

// CreateLogMetricRequest

// optional string parent = 1;
inline void CreateLogMetricRequest::clear_parent() {
  parent_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CreateLogMetricRequest::parent() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.CreateLogMetricRequest.parent)
  return parent_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateLogMetricRequest::set_parent(const ::std::string& value) {
  
  parent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.logging.v2.CreateLogMetricRequest.parent)
}
inline void CreateLogMetricRequest::set_parent(const char* value) {
  
  parent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.logging.v2.CreateLogMetricRequest.parent)
}
inline void CreateLogMetricRequest::set_parent(const char* value, size_t size) {
  
  parent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.logging.v2.CreateLogMetricRequest.parent)
}
inline ::std::string* CreateLogMetricRequest::mutable_parent() {
  
  // @@protoc_insertion_point(field_mutable:google.logging.v2.CreateLogMetricRequest.parent)
  return parent_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateLogMetricRequest::release_parent() {
  // @@protoc_insertion_point(field_release:google.logging.v2.CreateLogMetricRequest.parent)
  
  return parent_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateLogMetricRequest::set_allocated_parent(::std::string* parent) {
  if (parent != NULL) {
    
  } else {
    
  }
  parent_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), parent);
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.CreateLogMetricRequest.parent)
}

// optional .google.logging.v2.LogMetric metric = 2;
inline bool CreateLogMetricRequest::has_metric() const {
  return !_is_default_instance_ && metric_ != NULL;
}
inline void CreateLogMetricRequest::clear_metric() {
  if (GetArenaNoVirtual() == NULL && metric_ != NULL) delete metric_;
  metric_ = NULL;
}
inline const ::google::logging::v2::LogMetric& CreateLogMetricRequest::metric() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.CreateLogMetricRequest.metric)
  return metric_ != NULL ? *metric_ : *default_instance_->metric_;
}
inline ::google::logging::v2::LogMetric* CreateLogMetricRequest::mutable_metric() {
  
  if (metric_ == NULL) {
    metric_ = new ::google::logging::v2::LogMetric;
  }
  // @@protoc_insertion_point(field_mutable:google.logging.v2.CreateLogMetricRequest.metric)
  return metric_;
}
inline ::google::logging::v2::LogMetric* CreateLogMetricRequest::release_metric() {
  // @@protoc_insertion_point(field_release:google.logging.v2.CreateLogMetricRequest.metric)
  
  ::google::logging::v2::LogMetric* temp = metric_;
  metric_ = NULL;
  return temp;
}
inline void CreateLogMetricRequest::set_allocated_metric(::google::logging::v2::LogMetric* metric) {
  delete metric_;
  metric_ = metric;
  if (metric) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.CreateLogMetricRequest.metric)
}

// -------------------------------------------------------------------

// UpdateLogMetricRequest

// optional string metric_name = 1;
inline void UpdateLogMetricRequest::clear_metric_name() {
  metric_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UpdateLogMetricRequest::metric_name() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.UpdateLogMetricRequest.metric_name)
  return metric_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UpdateLogMetricRequest::set_metric_name(const ::std::string& value) {
  
  metric_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.logging.v2.UpdateLogMetricRequest.metric_name)
}
inline void UpdateLogMetricRequest::set_metric_name(const char* value) {
  
  metric_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.logging.v2.UpdateLogMetricRequest.metric_name)
}
inline void UpdateLogMetricRequest::set_metric_name(const char* value, size_t size) {
  
  metric_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.logging.v2.UpdateLogMetricRequest.metric_name)
}
inline ::std::string* UpdateLogMetricRequest::mutable_metric_name() {
  
  // @@protoc_insertion_point(field_mutable:google.logging.v2.UpdateLogMetricRequest.metric_name)
  return metric_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UpdateLogMetricRequest::release_metric_name() {
  // @@protoc_insertion_point(field_release:google.logging.v2.UpdateLogMetricRequest.metric_name)
  
  return metric_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UpdateLogMetricRequest::set_allocated_metric_name(::std::string* metric_name) {
  if (metric_name != NULL) {
    
  } else {
    
  }
  metric_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), metric_name);
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.UpdateLogMetricRequest.metric_name)
}

// optional .google.logging.v2.LogMetric metric = 2;
inline bool UpdateLogMetricRequest::has_metric() const {
  return !_is_default_instance_ && metric_ != NULL;
}
inline void UpdateLogMetricRequest::clear_metric() {
  if (GetArenaNoVirtual() == NULL && metric_ != NULL) delete metric_;
  metric_ = NULL;
}
inline const ::google::logging::v2::LogMetric& UpdateLogMetricRequest::metric() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.UpdateLogMetricRequest.metric)
  return metric_ != NULL ? *metric_ : *default_instance_->metric_;
}
inline ::google::logging::v2::LogMetric* UpdateLogMetricRequest::mutable_metric() {
  
  if (metric_ == NULL) {
    metric_ = new ::google::logging::v2::LogMetric;
  }
  // @@protoc_insertion_point(field_mutable:google.logging.v2.UpdateLogMetricRequest.metric)
  return metric_;
}
inline ::google::logging::v2::LogMetric* UpdateLogMetricRequest::release_metric() {
  // @@protoc_insertion_point(field_release:google.logging.v2.UpdateLogMetricRequest.metric)
  
  ::google::logging::v2::LogMetric* temp = metric_;
  metric_ = NULL;
  return temp;
}
inline void UpdateLogMetricRequest::set_allocated_metric(::google::logging::v2::LogMetric* metric) {
  delete metric_;
  metric_ = metric;
  if (metric) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.UpdateLogMetricRequest.metric)
}

// -------------------------------------------------------------------

// DeleteLogMetricRequest

// optional string metric_name = 1;
inline void DeleteLogMetricRequest::clear_metric_name() {
  metric_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeleteLogMetricRequest::metric_name() const {
  // @@protoc_insertion_point(field_get:google.logging.v2.DeleteLogMetricRequest.metric_name)
  return metric_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeleteLogMetricRequest::set_metric_name(const ::std::string& value) {
  
  metric_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.logging.v2.DeleteLogMetricRequest.metric_name)
}
inline void DeleteLogMetricRequest::set_metric_name(const char* value) {
  
  metric_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.logging.v2.DeleteLogMetricRequest.metric_name)
}
inline void DeleteLogMetricRequest::set_metric_name(const char* value, size_t size) {
  
  metric_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.logging.v2.DeleteLogMetricRequest.metric_name)
}
inline ::std::string* DeleteLogMetricRequest::mutable_metric_name() {
  
  // @@protoc_insertion_point(field_mutable:google.logging.v2.DeleteLogMetricRequest.metric_name)
  return metric_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeleteLogMetricRequest::release_metric_name() {
  // @@protoc_insertion_point(field_release:google.logging.v2.DeleteLogMetricRequest.metric_name)
  
  return metric_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeleteLogMetricRequest::set_allocated_metric_name(::std::string* metric_name) {
  if (metric_name != NULL) {
    
  } else {
    
  }
  metric_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), metric_name);
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.DeleteLogMetricRequest.metric_name)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v2
}  // namespace logging
}  // namespace google

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::google::logging::v2::LogMetric_ApiVersion> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::google::logging::v2::LogMetric_ApiVersion>() {
  return ::google::logging::v2::LogMetric_ApiVersion_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_google_2flogging_2fv2_2flogging_5fmetrics_2eproto__INCLUDED
